# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # Specify the package ecosystem
    directory: "/" # Directory where the package manifests are located
    schedule:
      interval: "weekly" # Schedule interval for updates
    commit-message:
      prefix: "chore(deps)" # Prefix for general dependencies
      prefix-development: "chore(dev-deps)" # Prefix for development dependencies
      include: "scope" # Include the scope (list of updated dependencies) in the commit message
